export const cityToTimezone: Record<string, string> = {
    'Amsterdam, NL': 'Europe/Amsterdam',
    'Arcadia, CA': 'America/Los_Angeles',
    'Asbury Park, NJ': 'America/New_York',
    'Bear Valley Springs, CA': 'America/Los_Angeles',
    'Berkeley, CA': 'America/Los_Angeles',
    'Boulder, CO': 'America/Denver',
    'Brooklyn, NY': 'America/New_York',
    'Cabo Bello, BCS, MX': 'America/Mazatlan',
    'Cabo San Lucas, BCS, MX': 'America/Mazatlan',
    'Cambridge, England, GB': 'Europe/London',
    'Carlsbad, CA': 'America/Los_Angeles',
    'Caryville, NY': 'America/New_York',
    'Chicago, IL': 'America/Chicago',
    'Cleveland, GA': 'America/New_York',
    'Cobb, CA': 'America/Los_Angeles',
    'Commerce, CA': 'America/Los_Angeles',
    'Concord, CA': 'America/Los_Angeles',
    'Cotati, CA': 'America/Los_Angeles',
    'Culver City, CA': 'America/Los_Angeles',
    'Denver, CO': 'America/Denver',
    'El Cajon, CA': 'America/Los_Angeles',
    'El Cuyo, MX': 'America/Merida',
    'El Segundo, CA': 'America/Los_Angeles',
    'Encinitas, CA': 'America/Los_Angeles',
    'Escondido, CA': 'America/Los_Angeles',
    'Eugene, OR': 'America/Los_Angeles',
    'Fair Oaks, CA': 'America/Los_Angeles',
    'Fort Lauderdale, FL': 'America/New_York',
    'Fremont, CA': 'America/Los_Angeles',
    'Fullerton, CA': 'America/Los_Angeles',
    'Gresham, OR': 'America/Los_Angeles',
    'Huntington Beach, CA': 'America/Los_Angeles',
    'Indianapolis, IN': 'America/Indiana/Indianapolis',
    'La Jolla, CA': 'America/Los_Angeles',
    'Lafayette, CA': 'America/Los_Angeles',
    'Laguna Hills, CA': 'America/Los_Angeles',
    'Laguna Woods, CA': 'America/Los_Angeles',
    'Lakewood, CO': 'America/Denver',
    'Lancaster, CA': 'America/Los_Angeles',
    'Las Vegas, NV': 'America/Los_Angeles',
    'Laytonville, CA': 'America/Los_Angeles',
    'Leesburg, VA': 'America/New_York',
    'Lisboa, PT': 'Europe/Lisbon',
    'Long Beach, CA': 'America/Los_Angeles',
    'Los Angeles, CA': 'America/Los_Angeles',
    'Marietta, GA': 'America/New_York',
    'Marina del Rey, CA': 'America/Los_Angeles',
    'Mendocino, CA': 'America/Los_Angeles',
    'Mobile, AL': 'America/Chicago',
    'Monte Rio, CA': 'America/Los_Angeles',
    'Montecito, CA': 'America/Los_Angeles',
    'Monterey, CA': 'America/Los_Angeles',
    'Montreal, QC': 'America/Toronto',
    'Moraga, CA': 'America/Los_Angeles',
    'Murrieta, CA': 'America/Los_Angeles',
    'Nashville, TN': 'America/Chicago',
    'Nevada City, CA': 'America/Los_Angeles',
    'New York, NY': 'America/New_York',
    'Newnan, GA': 'America/New_York',
    'North Bethesda, MD': 'America/New_York',
    'Novato, CA': 'America/Los_Angeles',
    'Oakland, CA': 'America/Los_Angeles',
    'Oxnard, CA': 'America/Los_Angeles',
    'Philadelphia, PA': 'America/New_York',
    'Piedmont, CA': 'America/Los_Angeles',
    'Plainfield, MA': 'America/New_York',
    'Portland, OR': 'America/Los_Angeles',
    'Poughkeepsie, NY': 'America/New_York',
    'Redwood City, CA': 'America/Los_Angeles',
    'Reno, NV': 'America/Los_Angeles',
    'Roswell, GA': 'America/New_York',
    'Sacramento, CA': 'America/Los_Angeles',
    'Saint Albans City, VT': 'America/New_York',
    'Salt Lake City, UT': 'America/Denver',
    'San Anselmo, CA': 'America/Los_Angeles',
    'San Antonio, TX': 'America/Chicago',
    'San Diego, CA': 'America/Los_Angeles',
    'San Francisco, CA': 'America/Los_Angeles',
    'San Jose, CA': 'America/Los_Angeles',
    'San Rafael, CA': 'America/Los_Angeles',
    'San Ramon, CA': 'America/Los_Angeles',
    'Santa Cruz, CA': 'America/Los_Angeles',
    'Santa Rosa, CA': 'America/Los_Angeles',
    'Santee, CA': 'America/Los_Angeles',
    'Seattle, WA': 'America/Los_Angeles',
    'Sebastopol, CA': 'America/Los_Angeles',
    'South Gate, CA': 'America/Los_Angeles',
    'South Pasadena, CA': 'America/Los_Angeles',
    'Southfield, MI': 'America/Detroit',
    'Split, Split-Dalmatia County, HR': 'Europe/Zagreb',
    'Sunnyvale, CA': 'America/Los_Angeles',
    'Tehachapi, CA': 'America/Los_Angeles',
    'Temple City, CA': 'America/Los_Angeles',
    'Toronto, ON, CA': 'America/Toronto',
    'Tuolumne, CA': 'America/Los_Angeles',
    'Tustin, CA': 'America/Los_Angeles',
    'Ukiah, CA': 'America/Los_Angeles',
    'Upper Lake, CA': 'America/Los_Angeles',
    'Vancouver, BC, CA': 'America/Vancouver',
    'Vista, CA': 'America/Los_Angeles',
    'Wantagh, NY': 'America/New_York',
    'Washington, DC': 'America/New_York',
    'Watervliet, MI': 'America/Detroit',
    'West Hollywood, CA': 'America/Los_Angeles',
    'Wilton Manors, FL': 'America/New_York',
}

export const getTimezoneFromCity = (cityName: string): string => {
    const key = Object.keys(cityToTimezone).find((key) => key.toLowerCase().includes(cityName.toLowerCase()))
    if (!key) return 'America/Los_Angeles'
    return cityToTimezone[key] || 'America/Los_Angeles'
}

export const getCityStateFromCity = (cityName: string): string => {
    // return key if cityname is in the cityToTimezone object
    let cityTrimmed = cityName.trim()
    if (cityTrimmed === '') return ''
    cityTrimmed = cityTrimmed.toLowerCase()
    const key = Object.keys(cityToTimezone).find((key) => key.toLowerCase().includes(cityTrimmed))
    return key || ''
}
