export const cityToTimezone: Record<string, string> = {
    'amsterdam, nl': 'Europe/Amsterdam',
    'arcadia, ca': 'America/Los_Angeles',
    'asbury park, nj': 'America/New_York',
    'bear valley springs, ca': 'America/Los_Angeles',
    'berkeley, ca': 'America/Los_Angeles',
    'boulder, co': 'America/Denver',
    'brooklyn, ny': 'America/New_York',
    'cabo bello, bcs, mx': 'America/Mazatlan',
    'cabo san lucas, bcs, mx': 'America/Mazatlan',
    'cambridge, england, gb': 'Europe/London',
    'carlsbad, ca': 'America/Los_Angeles',
    'caryville, ny': 'America/New_York',
    'chicago, il': 'America/Chicago',
    'cleveland, ga': 'America/New_York',
    'cobb, ca': 'America/Los_Angeles',
    'commerce, ca': 'America/Los_Angeles',
    'concord, ca': 'America/Los_Angeles',
    'cotati, ca': 'America/Los_Angeles',
    'culver city, ca': 'America/Los_Angeles',
    'denver, co': 'America/Denver',
    'el cajon, ca': 'America/Los_Angeles',
    'el cuyo, mx': 'America/Merida',
    'el segundo, ca': 'America/Los_Angeles',
    'encinitas, ca': 'America/Los_Angeles',
    'escondido, ca': 'America/Los_Angeles',
    'eugene, or': 'America/Los_Angeles',
    'fair oaks, ca': 'America/Los_Angeles',
    'fort lauderdale, fl': 'America/New_York',
    'fremont, ca': 'America/Los_Angeles',
    'fullerton, ca': 'America/Los_Angeles',
    'gresham, or': 'America/Los_Angeles',
    'huntington beach, ca': 'America/Los_Angeles',
    'indianapolis, in': 'America/Indiana/Indianapolis',
    'la jolla, ca': 'America/Los_Angeles',
    'lafayette, ca': 'America/Los_Angeles',
    'laguna hills, ca': 'America/Los_Angeles',
    'laguna woods, ca': 'America/Los_Angeles',
    'lakewood, co': 'America/Denver',
    'lancaster, ca': 'America/Los_Angeles',
    'las vegas, nv': 'America/Los_Angeles',
    'laytonville, ca': 'America/Los_Angeles',
    'leesburg, va': 'America/New_York',
    'lisboa, pt': 'Europe/Lisbon',
    'long beach, ca': 'America/Los_Angeles',
    'los angeles, ca': 'America/Los_Angeles',
    'marietta, ga': 'America/New_York',
    'marina del rey, ca': 'America/Los_Angeles',
    'mendocino, ca': 'America/Los_Angeles',
    'mobile, al': 'America/Chicago',
    'monte rio, ca': 'America/Los_Angeles',
    'montecito, ca': 'America/Los_Angeles',
    'monterey, ca': 'America/Los_Angeles',
    'montreal, qc': 'America/Toronto',
    'moraga, ca': 'America/Los_Angeles',
    'murrieta, ca': 'America/Los_Angeles',
    'nashville, tn': 'America/Chicago',
    'nevada city, ca': 'America/Los_Angeles',
    'new york, ny': 'America/New_York',
    'newnan, ga': 'America/New_York',
    'north bethesda, md': 'America/New_York',
    'novato, ca': 'America/Los_Angeles',
    'oakland, ca': 'America/Los_Angeles',
    'oxnard, ca': 'America/Los_Angeles',
    'philadelphia, pa': 'America/New_York',
    'piedmont, ca': 'America/Los_Angeles',
    'plainfield, ma': 'America/New_York',
    'portland, or': 'America/Los_Angeles',
    'poughkeepsie, ny': 'America/New_York',
    'redwood city, ca': 'America/Los_Angeles',
    'reno, nv': 'America/Los_Angeles',
    'roswell, ga': 'America/New_York',
    'sacramento, ca': 'America/Los_Angeles',
    'saint albans city, vt': 'America/New_York',
    'salt lake city, ut': 'America/Denver',
    'san anselmo, ca': 'America/Los_Angeles',
    'san antonio, tx': 'America/Chicago',
    'san diego, ca': 'America/Los_Angeles',
    'san francisco, ca': 'America/Los_Angeles',
    'san jose, ca': 'America/Los_Angeles',
    'san rafael, ca': 'America/Los_Angeles',
    'san ramon, ca': 'America/Los_Angeles',
    'santa cruz, ca': 'America/Los_Angeles',
    'santa rosa, ca': 'America/Los_Angeles',
    'santee, ca': 'America/Los_Angeles',
    'seattle, wa': 'America/Los_Angeles',
    'sebastopol, ca': 'America/Los_Angeles',
    'south gate, ca': 'America/Los_Angeles',
    'south pasadena, ca': 'America/Los_Angeles',
    'southfield, mi': 'America/Detroit',
    'split, split-dalmatia county, hr': 'Europe/Zagreb',
    'sunnyvale, ca': 'America/Los_Angeles',
    'tehachapi, ca': 'America/Los_Angeles',
    'temple city, ca': 'America/Los_Angeles',
    'toronto, on, ca': 'America/Toronto',
    'tuolumne, ca': 'America/Los_Angeles',
    'tustin, ca': 'America/Los_Angeles',
    'ukiah, ca': 'America/Los_Angeles',
    'upper lake, ca': 'America/Los_Angeles',
    'vancouver, bc, ca': 'America/Vancouver',
    'vista, ca': 'America/Los_Angeles',
    'wantagh, ny': 'America/New_York',
    'washington, dc': 'America/New_York',
    'watervliet, mi': 'America/Detroit',
    'west hollywood, ca': 'America/Los_Angeles',
    'wilton manors, fl': 'America/New_York',
}

export const getTimezoneFromCity = (cityName: string): string => {
    return cityToTimezone[cityName.toLowerCase()] || 'America/Los_Angeles'
}
